### ISSUE TITLE
TypeError: Cannot read property 'database' of undefined

### ISSUE THREAD

**Issue by nifl** [khaliqgant/remotee-sync#4]
I have a bootstrap config and renamed `system` dir. I've configured a remotee-sync.json based on the multiple environment example. Then, invoking;
`remotee-sync --ssh=staging` where 'staging' maps to an ssh-config alias in the .json
—results in the error pasted below.

```
/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:172
    if (_.multiple && !_.connection[_.env].database) {
                                          ^
TypeError: Cannot read property 'database' of undefined
    at dbCheck (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:172:43)
    at /usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:26:5
    at /usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:154:13
    at Object.methods.parseDB (/usr/local/lib/node_modules/remotee-sync/lib/methods.js:179:13)
    at fillConfig (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:152:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:24:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by khaliqgant** [comment]
Thanks for reporting. Would you also mind pasting in what you get if you run the command with a -d flag at the end? So it would be

```
remotee-sync --ssh=staging -d
```

It might very well be the same result, but just want to see if there is anything else in the response. Regardless, I'll take a look!

**Comment by nifl** [comment]
Here's a little more info. My remotee-sync.js is in the root dir.

```
Attempting to parse a remotee-sync.json config file
Attempting to locate a database.php file
/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:172
    if (_.multiple && !_.connection[_.env].database) {
                                          ^
TypeError: Cannot read property 'database' of undefined
    at dbCheck (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:172:43)
    at /usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:26:5
    at /usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:154:13
    at Object.methods.parseDB (/usr/local/lib/node_modules/remotee-sync/lib/methods.js:179:13)
    at fillConfig (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:152:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/remotee-sync/bin/remotee-sync.js:24:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by nifl** [comment]
And here's what my config file looks like. [edited pw's and host]

```
{
  "ssh" : {
      "staging" : "berzerker",
      "production" : "to-be-determined"
  },
  "location": "sql",
  "dumpName" : "coral-db.sql",
  "save" : "yes",
  "database" : {
      "local" : {
          "hostname" : "localhost",
          "username" : "vato",
          "password" : "acrazygoodpassword",
          "database" : "saku"
      },
      "production" : {
          "hostname" : "jingleheimer.cdvn8q960cl7v.us-west-2.rds.amazonaws.com",
          "username" : "cholo",
          "password" : "acrazygoodpassword",
          "database" : "coral"
      }
  }
}
```

**Comment by khaliqgant** [comment]
Great thanks, FYI, I plan to look at this tomorrow and will get back to you.

**Comment by khaliqgant** [comment]
The issue seems to be that you're trying to bring down your database from your staging environment

```
remotee-sync --ssh=staging
```

but in the remotee-sync.config you posted, you don't have a staging key to identify the credentials. That's why that error is popping up:

```
Cannot read property 'database' of undefined
if (_.multiple && !_.connection[_.env].database)
```

because the env in this case is staging, but that database property is empty because there is no staging key. 

I'm actually not 100% sure if having three environments will work as expected, will have to run some tests, but in theory your config database object would look like

```
"database" : {
      "local" : {
          "hostname" : "localhost",
          "username" : "vato",
          "password" : "acrazygoodpassword",
          "database" : "saku"
      },
      "production" : {
          "hostname" : "jingleheimer.cdvn8q960cl7v.us-west-2.rds.amazonaws.com",
          "username" : "cholo",
          "password" : "acrazygoodpassword",
          "database" : "coral"
      },
     "staging" : {
          "hostname" : "jinglemaster.cdvn8q960cl7v.us-west-2.rds.amazonaws.com",
          "username" : "cholos",
          "password" : "amadgoodpassword",
          "database" : "coralreef"
      }
  }
```

**Comment by khaliqgant** [comment]
Just tested 3 nested environments and see it does not work. I'll put in a fix to support multiple environments and update the documentation as well. When there are more than the expected environments, a `--env=staging-ec2` will be required. Thanks for bringing this to my attention!

**Comment by nifl** [comment]
Just caught up on this. Thank you
